server:
  port: 80
  servlet:
    context-path: /eprj
eprj:
  permit-clients: 219.159.20.64, 124.65.98.198,10.16.31.125,219.159.20.83,10.16.31.191,10.16.31.92
  daqWebAddress: https://www.guoanshuju.com/daqWeb
  ndrc:
    ftpServer: 10.16.31.241
    userName: daishuhua
    passWord: abc123
    fileDir: /var/ftp/pub/

  