server:
  port: 80
  servlet:
    context-path: /eprj
eprj:
  permit-clients: 219.159.20.64, 124.65.98.198,10.16.31.125,219.159.20.83,10.16.31.191,10.16.31.92
  daqWebAddress: https://www.guoanshuju.com/daqWeb
  ndrc:
    ftpServer: 103.83.44.206
    userName: GASQ
    passWord: 123456
    fileDir: /
  sqlserver:
    url: jdbc:sqlserver://39.107.69.242:1433;DatabaseName=Enjoy_Hq
    user: test
    password: gasq1qaz

  